name: untitled
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http:
  flutter_bloc:
  flutter_offline:
  google_maps_flutter: ^2.4.1
  custom_info_window: ^1.0.1
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/earth.jpg
   - assets/weather.png
   - assets/day.jpg
   - assets/night.jpg
   - screen_shots/night3.jpg
   - screen_shots/sunny.jpeg
   - screen_shots/world2.jpg
   - screen_shots/world3.jpg

